version: "3.8"

services:
  client:
    build:
      context: ./client
    ports:
      - "3000:3000"
    depends_on:
      - server
    environment:
      - http://localhost:3000=http://server:5000
    volumes:
      - ./client/src:/app/src
      - /client/src:/app/src/node_modules
    networks:
      - app-network
    command: "npm start"

  server:
    build:
      context: ./server
    ports:
      - "5000:5000"
    volumes:
      - ./server/src:/app/src
      - /server/src:/app/src/node_modules
    networks:
      - app-network
    command: "npm start"

networks:
  app-network:
    driver: bridge
